# FrontEnd Build
FROM node:12

WORKDIR /usr/app

COPY angular-app/ .

RUN npm ci

CMD ["npm", "build"]

# Backend
FROM python:3.8-slim

WORKDIR /usr/app

RUN python -m venv /usr/app/venv

COPY requirements.txt .

COPY . .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set the command to run your application
CMD ["cdk", "deploy"]