FROM python:3.8-slim

RUN apt-get update && \
    apt-get install -y nodejs npm && \
    npm install -g aws-cdk

#Frontend build
WORKDIR /usr/angular-app

COPY angular-app/ .

RUN npm ci && \
    npm run build

#Backend Build and deploy
WORKDIR /usr/app

RUN python -m venv /usr/app/venv

COPY backend/ .

# Install the Python dependencies
RUN pip install -r requirements.txt

# Set the command to run your application
CMD ["cdk", "deploy"]
